services:
    Jupi\DropzoneJsUploaderBundle\Service\DropzoneJsUploader:
        arguments: ['@request_stack']
        public: true

    jupi_dropzone_js_uploader:
        alias: Jupi\DropzoneJsUploaderBundle\Service\DropzoneJsUploader
        public: true
