services:
  jupi.dropzone_js_upload_manager:
    class: Jupi\DropzoneJsUploaderBundle\Service\UploadManager
    arguments: ["@request_stack", "@logger"]
    tags:
      - { name: monolog.logger, channel: dropzone_uploader }

  Jupi\DropzoneJsUploaderBundle\ParamConverter\ParamConverterRuntime:
    arguments: ["@jupi.dropzone_js_upload_manager"]
    tags:
      - {
          name: request.param_converter,
          converter: jupi.dropzone_js_converter,
          priority: false,
        }

  Jupi\DropzoneJsUploaderBundle\EventSubscriber\KernelSubscriber:
    arguments: ["@jupi.dropzone_js_upload_manager"]
    tags:
      - kernel.event_subscriber
