services:
  jupi.dropzone_js_upload_manager:
    class: Jupi\DropzoneJsUploaderBundle\Service\UploadManager
    arguments: ["@request_stack", "@logger"]
    tags:
      - { name: monolog.logger, channel: dropzone_uploader }

  Jupi\DropzoneJsUploaderBundle\ValueResolver\DropzoneJsValueResolver:
    arguments: ["@jupi.dropzone_js_upload_manager"]
    tags:
      - { name: controller.argument_value_resolver, priority: 101 }

  Jupi\DropzoneJsUploaderBundle\EventSubscriber\KernelSubscriber:
    arguments: ["@jupi.dropzone_js_upload_manager"]
    tags:
      - kernel.event_subscriber
